 const { DataTypes } = require('sequelize');
const { LEAD_STATUSES, VERIFICATION_STATUSES, APPLICATION_STATUSES, CRM_BUCKETS } = require('../utilities/constants');

module.exports = (sequelize) => {
  return sequelize.define('Lead', {
    id: { type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true },
    name: { type: DataTypes.STRING },
    email: { type: DataTypes.STRING },
    phone: { type: DataTypes.STRING(15), unique:true},
    city: { type: DataTypes.STRING },
    company: { type: DataTypes.STRING },
    lead_source: { type: DataTypes.STRING },
    company_category_id: { type: DataTypes.INTEGER },
    salary: { type: DataTypes.DECIMAL(10, 2) },
    address: { type: DataTypes.TEXT },
    gender: { type: DataTypes.ENUM('male', 'female', 'transgender', 'others'),allowNull:true },
    alternate_phones: {type:DataTypes.JSON, defaultValue:[]},
    verification_status: { 
      type: DataTypes.ENUM(...VERIFICATION_STATUSES), // Spread the array values into the ENUM type
      defaultValue: 'Under Review' // Set a default value
    },
    lead_status: { type: DataTypes.STRING, defaultValue: 'Not Contacted' },
    application_status : { type: DataTypes.ENUM(...APPLICATION_STATUSES) },
    is_rejected: { type: DataTypes.BOOLEAN, defaultValue: false },
    rejection_reason: { type: DataTypes.TEXT },
    rejected_by_id: { type: DataTypes.INTEGER },
    rejected_at : {type: DataTypes.DATE},
    verification_status_note : {type:DataTypes.TEXT},
    application_status_note: {type:DataTypes.TEXT},
    others_note: {type:DataTypes.TEXT},
    updated_by: { type: DataTypes.INTEGER },
    last_updated_status: { type: DataTypes.STRING },
    is_reassigned : {type: DataTypes.BOOLEAN, defaultValue: false },
    bereau_score: { type: DataTypes.DECIMAL(10, 0) },
    bereau_name: {type: DataTypes.STRING},
    closing_date: {type: DataTypes.DATE},
    verification_date: {type: DataTypes.DATE},
    login_date: {type: DataTypes.DATE},
    lead_bucket : {type: DataTypes.ENUM(...CRM_BUCKETS), defaultValue: 'PIPELINE_ENTRIES'},
    is_paid : { type: DataTypes.BOOLEAN, defaultValue: false },
    loan_amount: { type: DataTypes.DECIMAL(15,2), allowNull:true },
    prev_lead_sources: { type: DataTypes.JSON, defaultValue: [], allowNull: true },
    visit_count: { type: DataTypes.INTEGER, defaultValue:0, allowNull:true },
    product: { type: DataTypes.STRING },
    utm_campaign: { type: DataTypes.STRING, allowNull:true },
    prev_utm_campaigns: { type: DataTypes.JSON, defaultValue: [], allowNull: true },
    utm_source: { type: DataTypes.STRING, allowNull:true },
    prev_utm_sources: { type: DataTypes.JSON, defaultValue: [], allowNull: true },
    preferred_bank_name: { type: DataTypes.STRING },
    income_type: { type: DataTypes.STRING },
    customer_id: { type: DataTypes.INTEGER },
    fb_leadgen_id: { type: DataTypes.STRING },
    fb_form_id: { type: DataTypes.STRING },
    fb_ad_id: { type: DataTypes.STRING },
    status: { type: DataTypes.ENUM('active', 'inactive'), defaultValue: 'active' },
  }, { timestamps: true });
};
